                      -----------------------------
                      -- WINDOW DARK MODE IN LUA --
                      -----------------------------                   
-- Script and code made by T-Bar: https://www.youtube.com/@tbar7460 --
--    (please leave this message in the script, acts as credits)    --
--                                :D                                --